language: python
sudo: false
addons:
  apt:
    packages:
    - libssl-dev
    - libdb-dev
cache:
  pip: true
  directories:
  - eggs
  - downloads
  - openldap
matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.6"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
      dist: xenial
sudo: true
install:
  - pip install -r requirements-${PLONE_VERSION}.txt
  - buildout -Nc buildout-${PLONE_VERSION}.cfg buildout:download-cache=downloads code-analysis:return-status-codes=True "parts=test code-analysis coverage test-coverage testldap" annotate
  - buildout -Nc buildout-${PLONE_VERSION}.cfg buildout:download-cache=downloads code-analysis:return-status-codes=True "parts=test code-analysis coverage test-coverage testldap"
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - pip install coveralls
  - coveralls